### ISSUE TITLE
Github page for documentation

### ISSUE THREAD

**Issue by NicolaDonelli** [CGnal/python-ci-template#37]
It would be cool to have github page associated to any repo containing project's API documentation.
This would be achievable using a github action from taken from [this repo](https://github.com/marketplace/actions/github-pages-overwriter#what-is-it) with a workflow activated at each update on main branch that changes the `docs` folder using as source at the `docs/html` folder (the folder in which the `make docs` writes its outputs).
To that folder should be added also an empty `.nojekyll` file to avoid upload problems.

The idea I have in mind (yet to be tried!) would consist in the following steps:
1. Modify the init folder to create a `gh_pages` branch pushing it to the remote and delete its local version
2. Go to Settings > Pages and set the source to `gh_pages` with directory `/root`
3. Add the following github workflow to update the github page at every push on main branch

```
name: Build and Deploy GithubPage
# Inspired by https://github.com/rayluo/github-pages-overwriter/blob/dev/action.yml

env:
  SOURCE_DIR: docs/html
  TARGET_BRANCH: gh_pages

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Generate content
        run: make --directory=sphinx --file=Makefile html

      - name: Commit changes to target branch
        shell: bash
        run: |
            # The following 2 lines are not really necessary, because we do not intend to push current branch.
            # But we choose to use target branch name as a temporary local work branch,
            # thus avoid a potential error of committing to the trigger branch.
            git branch -f ${TARGET_BRANCH} HEAD
            git checkout ${TARGET_BRANCH}
            # Generate such a new file to make sure the subsequent commit would succeed
            # Such a file WITHOUT leading dot (.) is also visible in outcome website.
            # FYI: filename with leading dot (.) or underscore (_) would be ignored by Jekyll,
            # which Github Pages depends on. So we use a normal filename here.
            date > "${SOURCE_DIR}/publish_date.txt"
            # Genereate the .nojekyll file in source dir, to bypass Jekyll that would ignore with folders with leading 
            # dot (.) or underscore (_)
            if [ ! -f "${SOURCE_DIR}"/.nojekyll ]; then touch "${SOURCE_DIR}"/.nojekyll; fi
            # The commit and push happen to work without authentication
            # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
            git config user.name "Github Pages Overwriter"
            git config user.email "GithubPagesOverwriter@users.noreply.github.com"
            git add -A
            git commit -m "Publish GithubPage"

      - name: Push the build output to github pages
        shell: bash
        run: >  
            if [ "$SOURCE_DIR" == "." ]; then
              git push -f origin HEAD:refs/heads/$TARGET_BRANCH
            else
              git push -f origin `git subtree split --prefix=$SOURCE_DIR`:refs/heads/$TARGET_BRANCH
            fi

```
