### ISSUE TITLE
pre-commit/action

### ISSUE THREAD

**Issue by NicolaDonelli** [CGnal/python-ci-template#9]
While checking the repo for a small issue with actions I realized that the action [pre-commit/action](https://github.com/pre-commit/action) we use in "static-analysis-check" section of our workflow is actually deprecated.

In particular that repo suggest to switch to [pre-commit.ci](https://pre-commit.ci/), maybe it should be the case for us to consider that suggestion.

**Comment by afalcioni** [comment]
To solve issue #11 I created the confs folder and moved the `.pre-commit-config.yaml` file into it. As a consequence, all pre-commit commands now require the `--config` flag e.g.
```
pre-commit install --config=confs/.pre-commit-config.yaml
pre-commit run --config=confs/.pre-commit-config.yaml --all-files
```

In order to make it work, I tried to add this flag to the pre-commit/action configurations as well: 
```
static-analysis-check:
    name: Static Analysis
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2.2.2
      - uses: pre-commit/action@v2.0.3
         with:
          extra_args: --verbose --config=confs/.pre-commit-config.yaml 
```
but it didn't work. It turned out that [pre-commit/action does not support the --config flag](https://github.com/pre-commit/action/issues/94), so I temporarily disabled the action. 

This will have to be taken into account when switching to pre-commit.ci

@nromeoarena
